# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftOCR Camera' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftOCR'
  pod 'Alamofire'  
  pod 'NVActivityIndicatorView'
  # Pods for SwiftOCR Camera

end
